api/data/faq-it.tsx
insert in faq cancellation notification faq
=> feat: add annullamento faq

api/data/it/PA.tsx
**Description**
Modified the PA.tsx file to remove the "Login" button and to change the descriptive text, also added a link
**List of Changes**
Modified file PA.tsx
**Motivation and Context**
Edited a block on the landing page to make style changes
**How Has This Been Tested?**
**Screenshots (if appropriate):**
**Types of changes**
**Checklist:**
=> [PN-7970] - SEND-Modifica-blocco-landing-page

api/data/it/PA.tsx
Description
Modified the links to the api in PA.tsx
Modified file PA.tsx
Links to external resources modified
Checklist:
=> [B2BP-150] - Modified the links to the api

api/data/perfezionamento.tsx
The subtitle of the page and all the body parts of the central text have been changed
=> [B2BP-151] - Modified texts of the "perfezionamento" page (#8)

api/data/it/PA.tsx, api/data/it/PF.tsx, api/data/it/PH.tsx, api/data/it/PI.tsx
Description
Corrected some text on the SEND pages
To correct texts the "PD.tsx", "PI.tsx", "PF.tsx", "PA.tsx" and "PH.tsx" files were modified
Correct some texts
Checklist:
=> [B2BP-235] - Fine tuning on SEND showcase site

package.json, yarn.lock
Reverts pagopa/pn-showcase-site#15
=> Revert "build(deps): bump next from 13.4.8 to 13.5.0"

api/data/it/PA.tsx, src/components/NavigationBar.tsx
Description
Modified NavigationBar
Modified file NavigationBar.tsx
Edited a block on the landing page to make style changes
Checklist:
=> Nuova navbar

api/data/faq-it.tsx
Description
Modified the content of the FAQ page
Modified file faq-it.tsx
Edited the content of the page for updating contents
Checklist:
=> [B2BP-270] - FAQ update

api/data/it/PD.tsx
Description
Changed the display of the stack component in smartphone mode
Modified file PD.tsx
Edited a block on the landing page to make style changes
Checklist:
=> Modified stack component

api/data/it/PD.tsx
Description
Changes to the content of the "Documentazione" page
Changed the file PD.tsx
Make changes to the content
Checklist:
=> [B2BP-442] - "Documentazione" page changes

styles/default.css
Description
Changes to the style of app store CTAs
Changed the file default.css
Make changes to the UI 
Checklist:
=> [B2BP-450] - CTA app store changes

package.json, yarn.lock
Reverts pagopa/pn-showcase-site#50
=> Revert "Bump next from 13.4.8 to 14.1.1"

api/data/assistenza.tsx, api/data/it/PH.tsx, pages/assistenza.tsx, pages/faq/index.tsx, pages/index.tsx, styles/default.css
Description
B2BP-686 : changed spacing of chips
B2BP-685 : changes to the accordion ordering
B2BP-683 : changes to the cards's height 
B2BP-682 : changed "Leggi le FAQ delle istituzioni" CTA link
B2BP-681 : changed "Esplora le risorse per gli enti" CTA link
B2BP-680 : changed homepage's order of blocks
B2BP-679 : changes to contact block margin 
B2BP-678 : changed cards layout in assistance page
Changed the files "styles\default.css", "api\data\it\PH.tsx", "api\data\assistenza.tsx", "pages\faq\index.tsx", "pages\assistenza.tsx" and "pages\index.tsx".
Make changes to the UI and content …
=> Radd bug fix

model/index.ts, src/components/NavigationBar.tsx, styles/default.css
Description
Modified navigation bar and drawer.
Modified "src/components/NavigationBar.tsx" and "styles/default.css".
Renewal of navigation bar.
New features 
Checklist:
=> Drawer style fix

public/locales/it/common.json, public/locales/it/homepage.json, src/components/NavigationBar.tsx, src/pages/[lang]/index.tsx
Change label 'Aziende' with 'Imprese'
Change content
Run locally on localhost:3000
BEFORE
AFTER
=> [B2BP-962] - Change menu label

public/locales/fr/assistenza.json, public/locales/fr/cittadini.json, public/locales/fr/common.json, public/locales/fr/documenti.json, public/locales/fr/enti.json, public/locales/fr/faq.json, public/locales/fr/homepage.json, public/locales/fr/imprese.json, public/locales/fr/note-legali.json, public/locales/fr/numeri.json, public/locales/fr/perfezionamento.json, public/locales/fr/pickup.json, public/locales/fr/privacy.json
Consegna traduzioni Sito prodotto SEND in Francese
=> Consegna traduzioni Sito prodotto SEND in Francese

public/locales/it/pickup.json, src/components/Ritiro/OperatorsList.tsx, src/components/Ritiro/OperatorsTable.tsx, src/pages/[lang]/punti-di-ritiro-2a89b635-66f8-458a-a59b-8fb4146cd9d7.tsx
- Removed automatic scrolling on page load but kept it for page changes
- Added a loader to the store locator table
- Refactored the code for improved readability
Verify that everything works as expected on `it/punti-di-ritiro-2a89b635-66f8-458a-a59b-8fb4146cd9d7`.
Ensure that no changes have been introduced on `it/punti-di-ritiro`.
=> PN-13759 - Removed automatic scrolling on page load and added loader to the store locator table

aws-cdn-templates/one-cdn.yaml
=> PN-14101: Changed back CreateDnsRecordToCmsCloudfrontDist env value to prod after pipeline test

src/components/PickupPointsMap/index.tsx
On desktop try clicking on a marker and ensure that the drawer opens
=> fix(PN-14861): show drawer also on desktop marker click

public/locales/it/common.json, src/components/MuiItaliaAutocomplete/index.tsx, src/components/PickupPointsAutocomplete/index.tsx, src/components/PickupPointsMap/MapControls.tsx, src/pages/[lang]/mappa-punti-di-ritiro.tsx, src/pages/[lang]/punti-di-ritiro-2a89b635-66f8-458a-a59b-8fb4146cd9d7.tsx
this PR fixes a bug on iOS preventing the user from editing the autocomplete input after moving the focus on another component
test using voiceover on iOS and verify the TextField works as expected.
=> fix: fix autocomplete a11y on iOS

src/components/ErrorBox/index.tsx, src/components/PickupPointsList/index.tsx, src/components/PickupPointsMap/index.tsx, src/pages/[lang]/mappa-punti-di-ritiro.tsx
This PR is linked to https://github.com/pagopa/b2b-portals/pull/665, so please ensure that the message format matches the one defined in that PR
=> fix(PN-14858): send message to iframe parent to scroll to section outside iframe
